### ISSUE TITLE
1 User Collection

### ISSUE THREAD

**Issue by DavevonH** [Rick1Marques/star-wars-bazar-app#13]
## Value proposition

As a user
I want to be able to access my collection
so that I can have an overview of the starships I own

## Description

![Image](https://github.com/Rick1Marques/star-wars-bazar-app/assets/140090722/1d6ec35b-dc79-4576-af69-6434cd2f49ab)

## Acceptance criteria

- [ ] By clicking the my collection link, the user will be directed to the "My collection" page
  
- [ ] The "My collection" page shows an overview of the user's starships

- [ ] Each starship shows the following information:
    - Name of the starship
    - Image of the starship

- [ ] by Clicking the back arrow the user will be redirected to the "User's profile"

## Tasks

- [ ] List the tasks that need to be performed within the dev team

```

**Comment by ahohnsen** [comment]
Heyho 🙌 

The user story is well written, well done.

Please, keep in mind that we do not want to include items, which do not have a function yet.
If I remember correctly, at this point you do not have the selling list. Therefore it should not be included in your scribble.

I added a similar comment in another related US: https://github.com/users/Rick1Marques/projects/1/views/1?pane=issue&itemId=39015843

**Comment by B-Baumeister** [comment]
Sieht super aus! Viel Erfolg! 🚀
