### ISSUE TITLE
US 6 New Offer

### ISSUE THREAD

**Issue by DavevonH** [Rick1Marques/star-wars-bazar-app#14]
## Value proposition

As a user
I want to have the option to sell a starship from the collection
so that I can get rid of the starship i don't want to have anymore and to earn some credits

## Description

![Image](https://github.com/Rick1Marques/star-wars-bazar-app/assets/140090722/116cb4ff-bc37-443d-8bf4-693166ffc635)

## Acceptance criteria

- [ ] There is a sell link for each starship which directs the user to the "New offer" page if the user wants to offer 
 the starship for sale
- [ ] On the "New offer" page the following information will be shown:
        - Image of the starship
        - Detailed information of the starship
        - Input field where the user can set a price for the starship
 
- [ ] by Clicking the back arrow the user will be redirected to the "My collection" page

## Tasks

- [ ] List the tasks that need to be performed within the dev team

```

**Comment by ahohnsen** [comment]
Hi!

I have a question/suggestion:

I feel like it would be nice to have a confirmation button to finalize the sale. Right now, it seems like my starship will be on offer as soon as I enter a price. 🤔 What do you think?

**Comment by ahohnsen** [comment]
Me again 🙂 I just saw your next user story. Please merge these two together as I mentioned in the comment for your next user story.
