### ISSUE TITLE
US 7 User's selling list

### ISSUE THREAD

**Issue by DavevonH** [Rick1Marques/star-wars-bazar-app#15]
## Value proposition

As a user
I want to be able to access my selling list
so that I can have an overview of the starship I'm currently offering for sale and delete offers from my selling list

## Description

![Image](https://github.com/Rick1Marques/star-wars-bazar-app/assets/140090722/49c46dd5-508b-4b0d-901a-56d630a39a0e)

## Acceptance criteria

- [ ] By clicking the "My selling list" link, the user will be directed to the "My selling list" page
  
- [ ] The "My selling list" page shows an overview of the starships the user is offering

- [ ] Each starship shows the following information:
    - Name of the starship
    - Image of the starship
    - A delete offer button 

- [ ] By Clicking the back arrow the user will be redirected to the "User's profile"

## Tasks

- [ ] List the tasks that need to be performed within the dev team

```

**Comment by ahohnsen** [comment]
Nice job 🙌🏼 

Maybe it would be also nice to show the price in the selling list to get a quick overview 🙂

**Comment by shrocket** [comment]
Hello, and thank you for again allowing me to look at your work!

- When I clicked on the "My selling list" list, I was directed to the "My selling list" page! (the color of the link, however, made it very difficult to read)
- The "My selling list" page showed me an overview!
- Each item in the list showed name, image, and price!
- Because I couldn't delete starships from the list, I couldn't check if the "Currently you are not offering any starships" message showed.
- There is no back arrow, there is only the nav bar. The nav bar still works!
