### ISSUE TITLE
Submit offer

### ISSUE THREAD

**Issue by DavevonH** [Rick1Marques/star-wars-bazar-app#16]
## Value proposition

As a user
I want to be able to submit my offering for the selected starship
so that it appears on the marketplace and my selling list

## Description

![Image](https://github.com/Rick1Marques/star-wars-bazar-app/assets/140090722/e1d22fa4-c16a-42f1-a8d5-2297016886fb)

## Acceptance criteria

- [ ] There is a submit button underneath the new offer form
    - [ ] after clicking, the starship will be added to the "My selling list" and the "Marketplace"
      and will no longer be visible in the "My collection" list
- [ ] after submitting the user will be directed to the "My selling list" page where the user can see the new offer

## Tasks

- [ ] List the tasks that need to be performed within the dev team

```

**Comment by ahohnsen** [comment]
Hey there!

This user story should be merged with the previous one. Your feature is to offer a starship for sale. This includes specifying a price and to submit, in order to create a new offer.
