### ISSUE TITLE
US  10 - User Login

### ISSUE THREAD

**Issue by bermyu** [Rick1Marques/star-wars-bazar-app#26]
## Value proposition

As a user
I want to be able to access to my account
so that I can buy and sell starships.

## Description

The main user has already saved in the backend structure with the User.findById("6512ae2005ae4d31f6d82cf7")
So the main user is always logged in.

## Acceptance criteria

- [ ] Since the main user is already saved in the backend structure, on the frontend there won't be any login page.

## Tasks

- [ ] Create branch "feature/user-login"
- [ ] Create "hooks" file
- [ ] Create function useUser and fetch the data
- [ ] Create page/users/login.js
- [ ] Fetch the user[0] into the mainUser
- [ ] Import useUser to the _app.js
- [ ] Pass the mainUser as props to the Components
