### ISSUE TITLE
Remove an offer from user listings

### ISSUE THREAD

**Issue by DavevonH** [Rick1Marques/star-wars-bazar-app#28]
## Value proposition

As a user
I want to be able to delete a starship from my selling list
so that it is no longer offered on the marketplace

## Description

![Image](https://github.com/Rick1Marques/star-wars-bazar-app/assets/140090722/6cd1f375-6922-4b19-95db-bf1edff8d058)

## Acceptance criteria

- [ ] The user should be able to delete a starship from her/his listings
- [ ] When pressing the delete button the starship needs to disappear from the listings and will be added to the my collection
- [ ] When pressing the delete button the user will get an alert message 

## Tasks

- [ ] Create feature branch delete
- [ ] Add deleteListing function in the api.js
- [ ] Add delete method in the listing [id].js
- [ ] Add delete button in the ListingCard
- [ ] Add onClick and onDelete function

```
