### ISSUE TITLE
US 12 - Update an offer from user listing (e.g. price)

### ISSUE THREAD

**Issue by bermyu** [Rick1Marques/star-wars-bazar-app#31]
## Value proposition

As a user
I want to be able to delete a starship from my selling list
so that it is no longer offered on the marketplace

## Acceptance criteria

- [ ] The user should be able to delete a starship from her/his listings
- [ ] When pressing the delete button the starship needs to disappear from the listings and will be added to the my collection
- [ ] When pressing the delete button the user will get an alert message 

## Tasks

- [ ] Create feature branch delete
- [ ] Add deleteListing function in the api.js
- [ ] Add delete method in the listing [id].js
- [ ] Add delete button in the ListingCard
- [ ] Add onClick and onDelete function

```

**Comment by bermyu** [comment]
![Image](https://github.com/Rick1Marques/star-wars-bazar-app/assets/76650123/ce2e7385-a7ad-480a-9753-d0b8895361ed)
